docs: mention install step
Without npm install, running create-local-addon after
`npm install -g` fails with a "Error: Cannot find module 'minimist'"
error due to the globally installed version missing its deps.