fix: address deprecated callback feature in yeoman-environment
Here's the error that was showing:

```
~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:985
      throw new Error('Callback support have been removed.');
            ^

Error: Callback support have been removed.
    at Environment.run (~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:985:13)
    at Object.<anonymous> (~/src/local/create-local-addon/index.js:28:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```