Upgrade deps (#18)
* docs: include steps to install a local version of this repo for dev

* fix: upgrade yeoman deps to address dependabot vulns

* style: prettier save

* fix: address deprecated callback feature in yeoman-environment

Here's the error that was showing:

```
~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:985
      throw new Error('Callback support have been removed.');
            ^

Error: Callback support have been removed.
    at Environment.run (~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:985:13)
    at Object.<anonymous> (~/src/local/create-local-addon/index.js:28:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

* fix: upgrade insight

Fixes an issue when trying to run this tool on a newer version of
MacOS. Specific error was:

```
~/src/local/create-local-addon/node_modules/macos-release/index.js:26
        const [name, version] = nameMap.get(release);
                                ^

TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (~/src/local/create-local-addon/node_modules/macos-release/index.js:26:26)
    at osName (~/src/local/create-local-addon/node_modules/os-name/index.js:21:18)
    at new Insight (~/src/local/create-local-addon/node_modules/insight/lib/index.js:37:13)
    at new LocalAddonGenerator (~/src/local/create-local-addon/app/index.js:93:24)
    at Environment.instantiate (~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:812:23)
    at Environment.create (~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:784:17)
    at instantiateAndRun (~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:999:36)
    at Environment.run (~/src/local/create-local-addon/node_modules/yeoman-environment/lib/environment.js:1016:12)
    at Object.<anonymous> (~/src/local/create-local-addon/index.js:28:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

* fix: upgrade node-fetch to address dependabot vuln